# Generated by Django 2.2.2 on 2019-07-05 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20190704_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionconfig',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 12, 16, 48, 86749)),
        ),
        migrations.AlterField(
            model_name='electionconfig',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 12, 16, 48, 86718)),
        ),
    ]
