# Generated by Django 2.2.2 on 2019-07-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockNo', models.IntegerField(unique=True)),
                ('ParentHash', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
