# Generated by Django 2.2.2 on 2019-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hash', models.CharField(max_length=128)),
                ('parent_hash', models.CharField(max_length=128)),
                ('database_hash', models.TextField(unique=True)),
                ('source_code_hash', models.TextField(unique=True)),
                ('candidate_votes', models.TextField(blank=True, null=True)),
                ('electors', models.TextField(blank=True, null=True)),
                ('timestamp_iso', models.CharField(max_length=30)),
                ('total_votes', models.IntegerField()),
            ],
        ),
    ]
