# Generated by Django 2.2.2 on 2019-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_bblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bblock',
            name='database_hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bblock',
            name='source_code_hash',
            field=models.TextField(),
        ),
    ]
